# fly.toml app configuration file generated for node-sqlite-fly on 2024-04-09T17:57:41-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'node-sqlite-fly'
primary_region = 'sjc'

[build]

[[mounts]]
  source = 'data'
  destination = '/data'
  initial_size = '1GB'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
